# executor-onboard.ps1
# One-click self-registration for a HelloAI EXECUTOR agent (external Agent onboarding).
#   S1 POST /api/agents/register        -> { apiKey, id }   (idempotent=true reuses the same agent by name)
#   S2 GET  /api/agents/getMySkill      -> role SKILL.md with apiKey/baseUrl placeholders substituted
#   S3 write executor-config.json (runtime, gitignored) + .executor-onboarding.md (handoff doc)
# Prereq: backend up on BaseUrl and agent.allow-registration=true (default true in application.yml).
# Usage:
#   powershell -File scripts/powershell/executor-onboard.ps1
#   powershell -File scripts/powershell/executor-onboard.ps1 -BaseUrl http://localhost:6565 -Name codex-executor

[CmdletBinding()]
param(
    [string]$BaseUrl = 'http://localhost:6565',
    [string]$Name = 'codex-executor',
    [string]$Role = 'EXECUTOR',
    [string]$Description = 'HelloAI external EXECUTOR agent (Codex CLI)',
    [string[]]$Skills = @('shell', 'powershell', 'eng-code-review', 'eng-verification', 'eng-doc-standard'),
    [switch]$SkipSkill
)

$ErrorActionPreference = 'Stop'

# ------------------------------------------------------------
# UTF-8 encoding header (repo rule 6) - avoid CJK garbled output
# ------------------------------------------------------------
$script:Utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[Console]::InputEncoding  = [System.Text.Encoding]::UTF8
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
$OutputEncoding           = $script:Utf8NoBom

$ScriptDir = $PSScriptRoot
if (-not $ScriptDir) { $ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Definition }
$RepoRoot  = Split-Path -Parent (Split-Path -Parent $ScriptDir)
$ConfigPath = Join-Path $ScriptDir 'executor-config.json'
$OnboardPath = Join-Path $RepoRoot '.executor-onboarding.md'
$SkillOutPath = Join-Path $ScriptDir 'executor-SKILL.md'

Add-Type -AssemblyName System.Net.Http
$client = New-Object System.Net.Http.HttpClient
$client.Timeout = [TimeSpan]::FromSeconds(30)

function Post-Json($uri, $bodyObject, $bearer) {
    if ($bearer) {
        $client.DefaultRequestHeaders.Authorization =
            New-Object System.Net.Http.Headers.AuthenticationHeaderValue('Bearer', $bearer)
    } else {
        $client.DefaultRequestHeaders.Authorization = $null
    }
    $json = if ($null -eq $bodyObject) { '{}' } else { $bodyObject | ConvertTo-Json -Depth 10 -Compress }
    $content = New-Object System.Net.Http.StringContent($json, $script:Utf8NoBom, 'application/json')
    $resp = $client.PostAsync(($BaseUrl + $uri), $content).GetAwaiter().GetResult()
    $bytes = $resp.Content.ReadAsByteArrayAsync().GetAwaiter().GetResult()
    $text = $script:Utf8NoBom.GetString($bytes)
    return ($text | ConvertFrom-Json)
}

function Get-Json($uri, $bearer) {
    $client.DefaultRequestHeaders.Authorization =
        New-Object System.Net.Http.Headers.AuthenticationHeaderValue('Bearer', $bearer)
    $resp = $client.GetAsync(($BaseUrl + $uri)).GetAwaiter().GetResult()
    $bytes = $resp.Content.ReadAsByteArrayAsync().GetAwaiter().GetResult()
    $text = $script:Utf8NoBom.GetString($bytes)
    return ($text | ConvertFrom-Json)
}

Write-Host '=== HelloAI executor onboarding ==='
Write-Host ('baseUrl = ' + $BaseUrl)
Write-Host ('name    = ' + $Name)

# ---- S1: one-click self-registration (idempotent by name) ----
$regBody = @{
    name        = $Name
    role        = $Role
    description = $Description
    idempotent  = $true
    skills      = $Skills
}
$reg = Post-Json '/api/agents/register' $regBody $null
if ($reg.code -ne 200) {
    Write-Host ('[FAIL] register -> code=' + $reg.code + ' msg=' + $reg.msg)
    exit 1
}
$apiKey  = [string]$reg.data.apiKey
$agentId = [string]$reg.data.id
if ([string]::IsNullOrWhiteSpace($apiKey)) { Write-Host '[FAIL] register returned empty apiKey'; exit 1 }
Write-Host '[PASS] S1 register'
Write-Host ('       agentId = ' + $agentId)
Write-Host ('       apiKey  = ' + $apiKey.Substring(0, [Math]::Min(12, $apiKey.Length)) + '...')

# ---- S2: fetch the role SKILL.md generated by the platform ----
$skillLen = 0
if (-not $SkipSkill) {
    $skill = Get-Json '/api/agents/getMySkill' $apiKey
    if ($skill.code -ne 200) {
        Write-Host ('[WARN] S2 getMySkill -> code=' + $skill.code + ' msg=' + $skill.msg)
    } else {
        $content = [string]$skill.data.content
        $skillLen = $content.Length
        [IO.File]::WriteAllText($SkillOutPath, $content, $script:Utf8NoBom)
        Write-Host '[PASS] S2 getMySkill'
        Write-Host ('       role=' + $skill.data.role + '  chars=' + $skillLen + '  saved=' + $SkillOutPath)
    }
}

# ---- S3: runtime config (apiKey; gitignored) + handoff doc ----
$config = [ordered]@{
    baseUrl       = $BaseUrl
    apiKey        = $apiKey
    agentId       = $agentId
    agentName     = $Name
    role          = $Role
    maxConcurrent = 1
    ttlMinutes    = 30
    skills        = ($Skills -join ',')
}
[IO.File]::WriteAllText($ConfigPath, ($config | ConvertTo-Json -Depth 4), $script:Utf8NoBom)
Write-Host '[PASS] S3 runtime config written'
Write-Host ('       ' + $ConfigPath)

$onboard = @()
$onboard += '# Executor Onboarding (one-click registration result)'
$onboard += ''
$onboard += 'Generated by `scripts/powershell/executor-onboard.ps1`.'
$onboard += ''
$onboard += '| Field | Value |'
$onboard += '|---|---|'
$onboard += ('| Agent ID | ' + $agentId + ' |')
$onboard += ('| Name | ' + $Name + ' |')
$onboard += ('| Role | ' + $Role + ' |')
$onboard += ('| API Key | ' + $apiKey + ' |')
$onboard += ('| Base URL | ' + $BaseUrl + ' |')
$onboard += ('| Skills | ' + ($Skills -join ', ') + ' |')
$onboard += ''
$onboard += '## Next steps'
$onboard += ''
$onboard += '```powershell'
$onboard += 'powershell -File scripts/powershell/executor-duty.ps1 -Action checkIn'
$onboard += 'powershell -File scripts/powershell/executor-duty.ps1 -Action poll  -Rounds 5 -IntervalSeconds 30'
$onboard += 'powershell -File scripts/powershell/executor-duty.ps1 -Action checkOut'
$onboard += '```'
[IO.File]::WriteAllLines($OnboardPath, $onboard, $script:Utf8NoBom)
Write-Host '[PASS] S3 onboarding doc written'
Write-Host ('       ' + $OnboardPath)

$client.Dispose()
Write-Host 'DONE'
