#!/usr/bin/env zsh
# ============================================================
# helloai Phase0 C3 Step2 event-chain verifier (verify-c3-events.sh, macOS/Linux)
# 移植自 scripts/powershell/verify-c3-events.ps1。按验收标准 3/4/5 生成三支只读 SQL 探针，
# 若通道可用（本机 psql 或 docker helloai-postgres）则自动执行断言，否则落盘 + 提示走会话内 MCP：
#   P1 事件成对性：route=agent_runtime 子任务的 agent_started / agent_completed 计数，无孤儿
#      （孤儿 = completed < started 且 status 不在豁免集合；豁免 = IN_PROGRESS/RUNNING 在飞态
#        + BLOCKED/DEAD_LETTER/CANCELLED/PENDING/PENDING_PLAN_REVIEW/PAUSED 无事件语义态，
#        与后端 EventReconciliationServiceImpl 跳过契约对齐——异常中断路径（如 execute_failed）
#        不补发 agent_completed 属预期，非事件链缺陷）
#   P2 终态投影：route=agent_runtime 子任务业务状态 vs 末条事件（B3 五态映射），无 MISMATCH
#   P3 执行记录：agent_execution_record RUNNING 龄 > STUCK_MINUTES 才判滞留（默认 15min）
# Ref: doc/design/HelloAI_Phase0_C3_双轨切换预研.md（六章验收标准 3/4/5）
#      .agents/skills/helloai-preflight/SKILL.md（规则 6：UTF-8 头）
# 用法（项目根）：
#   ./scripts/shell/verify-c3-events.sh
#   DB_HOST=localhost PG_CONTAINER=helloai-postgres ./scripts/shell/verify-c3-events.sh
# 参数（环境变量）：DB_HOST DB_PORT DB_USER DB_NAME PG_CONTAINER STUCK_MINUTES
# ============================================================

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
source "$SCRIPT_DIR/c3-common.sh"

need_cmd awk

# P3 滞留阈值（分钟）：RUNNING 执行记录 update_time 距今超过此值才判滞留，
# 避免把正常在飞的 LLM 执行（单次可达数分钟）误判为卡死。默认 15min，可用环境变量覆盖。
STUCK_MINUTES="${STUCK_MINUTES:-15}"

# ============================================================
# S1: emit event-chain SQL probes (3 read-only)
# ============================================================
print -r -- "==== S1: emit event-chain SQL probes ===="
probe_file="$TMP_DIR/c3-events-probe.sql"
rm -f "$probe_file"
cat >"$probe_file" <<'SQL'
-- ============================================================
-- C3 Step 2 event-chain probe (generated by verify-c3-events.sh)
-- 只读；期望 P1 无孤儿 / P2 无 MISMATCH / P3 0 行
-- 执行通道：本地 psql / docker exec helloai-postgres / 会话内 MCP postgres_helloai_dev
-- ============================================================

-- P1 事件成对性：route=agent_runtime 子任务的 started/completed 计数。
-- 期望：每行 completed_cnt >= started_cnt（执行中 IN_PROGRESS 允许相等）。
--       孤儿 = completed_cnt < started_cnt 且 status 不在豁免集合。
--       豁免（与后端 EventReconciliationServiceImpl 跳过契约一致）：
--       IN_PROGRESS/RUNNING（在飞态）+ BLOCKED/DEAD_LETTER/CANCELLED/PENDING/
--       PENDING_PLAN_REVIEW/PAUSED（无事件语义态，异常中断不补发 completed 属预期）。
WITH rt AS (
    SELECT DISTINCT sub_task_id
    FROM task_timeline
    WHERE event_type = 'sub_task_execution_command_consume'
      AND payload->>'route' = 'agent_runtime'
      AND deleted = 0
)
SELECT rt.sub_task_id, s.title, s.status,
       (SELECT COUNT(*) FROM agent_event e
         WHERE e.sub_task_id = rt.sub_task_id AND e.deleted = 0
           AND e.event_type = 'agent_started')  AS started_cnt,
       (SELECT COUNT(*) FROM agent_event e
         WHERE e.sub_task_id = rt.sub_task_id AND e.deleted = 0
           AND e.event_type = 'agent_completed') AS completed_cnt
FROM rt JOIN sub_task s ON s.id = rt.sub_task_id
ORDER BY rt.sub_task_id;

-- P2 终态投影：route=agent_runtime 子任务业务状态 vs 末条事件（B3 五态映射）。
-- 期望：无 mismatch 行（DONE 末条应为 review_approved；REVIEW 为 agent_completed/review_started；
--       REWORK 为 review_rejected/rework_started）。人工验收路径埋点已补齐（LOG-20260903-007）。
-- 契约对齐 1：复刻后端 EventReconciliationServiceImpl——非语义状态（PENDING/PENDING_PLAN_REVIEW/
--       PAUSED/BLOCKED/CANCELLED/DEAD_LETTER）跳过校验，标 'SKIP' 而非 'MISMATCH'。
-- 契约对齐 2：人工验收存量豁免（LOG-20260904-004）——B2 埋点补齐（74993cc）前的人工验收
--       仅落 timeline 不落 agent_event，存在 sub_task_manual_review_passed 的 DONE 允许
--       末条为 agent_completed（修复后新验收均落 review_approved，不受影响）。
WITH rt AS (
    SELECT DISTINCT sub_task_id
    FROM task_timeline
    WHERE event_type = 'sub_task_execution_command_consume'
      AND payload->>'route' = 'agent_runtime'
      AND deleted = 0
), proj AS (
    SELECT s.id, s.status,
           (SELECT e.event_type FROM agent_event e
             WHERE e.sub_task_id = s.id AND e.deleted = 0
             ORDER BY e.create_time DESC, e.id DESC LIMIT 1) AS last_event
    FROM rt JOIN sub_task s ON s.id = rt.sub_task_id
)
SELECT p.id, p.status, p.last_event,
       CASE
           WHEN p.status IN ('PENDING','PENDING_PLAN_REVIEW','PAUSED','BLOCKED','CANCELLED','DEAD_LETTER') THEN 'SKIP'
           WHEN
           (p.status='ASSIGNED' AND p.last_event='task_assigned') OR
           (p.status='IN_PROGRESS' AND p.last_event IN ('agent_started','context_built','tool_call_started','tool_call_completed','skill_resolved','tool_resolved','environment_resolved')) OR
           (p.status='REVIEW' AND p.last_event IN ('agent_completed','review_started')) OR
           (p.status='REWORK' AND p.last_event IN ('review_rejected','rework_started')) OR
           (p.status='DONE' AND p.last_event='review_approved') OR
           (p.status='DONE' AND p.last_event='agent_completed' AND EXISTS (
               SELECT 1 FROM task_timeline tt
               WHERE tt.sub_task_id = p.id
                 AND tt.event_type = 'sub_task_manual_review_passed'
                 AND tt.deleted = 0))
       THEN 'ok' ELSE 'MISMATCH' END AS verdict
FROM proj p
ORDER BY p.id;

-- P3 执行记录滞留：RUNNING 状态执行记录 + 距 update_time 的分钟龄 age_min。
-- 滞留判定 = age_min > STUCK_MINUTES（正常在飞 LLM 执行龄小，不计滞留；阈值见脚本头）。
SELECT id, sub_task_id, status,
       EXTRACT(EPOCH FROM (now() - update_time)) / 60 AS age_min,
       start_time, update_time
FROM agent_execution_record
WHERE status = 'RUNNING' AND deleted = 0
ORDER BY update_time DESC;
SQL
[[ -f "$probe_file" ]] && assert_pass 1 "S1" "probe written: $probe_file" || assert_pass 0 "S1" "probe write failed"

# ============================================================
# S2: db channel auto-run (optional)
# ============================================================
print -r -- "==== S2: db channel auto-run (optional) ===="
probe_out="$TMP_DIR/c3-events-probe.out"
rm -f "$probe_out"
DB_MANUAL=0

if run_probe_sql "$probe_file" "$probe_out"; then
  # P1 孤儿：仅对 started/completed 均为纯整数的行判定（以此与 P3 时间戳列区分）
  # 豁免集合与后端跳过契约对齐（BLOCKED 等非语义终态不要求事件成对）
  exempt='IN_PROGRESS|RUNNING|BLOCKED|DEAD_LETTER|CANCELLED|PENDING|PENDING_PLAN_REVIEW|PAUSED'
  orphan_n="$(awk -F'|' -v ex="$exempt" 'NF>=5 && $4 ~ /^[0-9]+$/ && $5 ~ /^[0-9]+$/ && ($4+0)>($5+0) && $3 !~ "^(" ex ")$"' "$probe_out" 2>/dev/null | wc -l | tr -d '[:space:]')"; orphan_n="${orphan_n:-0}"
  mismatch_n="$(grep -Fc 'MISMATCH' "$probe_out" 2>/dev/null)"; mismatch_n="${mismatch_n:-0}"
  running_n="$(awk -F'|' -v thr="$STUCK_MINUTES" 'NF>=6 && $3=="RUNNING" && ($4+0)>thr' "$probe_out" 2>/dev/null | wc -l | tr -d '[:space:]')"; running_n="${running_n:-0}"

  [[ "$orphan_n" == "0" ]] && assert_pass 1 "S2" "P1 orphans=0" || assert_pass 0 "S2" "P1 orphans=$orphan_n"
  [[ "$mismatch_n" == "0" ]] && assert_pass 1 "S2" "P2 mismatches=0" || assert_pass 0 "S2" "P2 mismatches=$mismatch_n"
  [[ "$running_n" == "0" ]] && assert_pass 1 "S2" "P3 RUNNING stuck(>${STUCK_MINUTES}min)=0" || assert_pass 0 "S2" "P3 RUNNING stuck(>${STUCK_MINUTES}min)=$running_n"
  head -20 "$probe_out" | while IFS= read -r row; do [[ -n "$row" ]] && print -r -- "S2 row: $row"; done
else
  DB_MANUAL=1
  print -r -- "S2 NOTE: 本机无 psql 且未见 docker 容器 [$PG_CONTAINER]；请经会话内 MCP(postgres_helloai_dev) 执行 $probe_file，"
  print -r -- "        确认：P1 无孤儿 / P2 无 MISMATCH / P3 0 行"
fi

# ============================================================
# S3: summary
# ============================================================
print -r -- "==== SUMMARY: PASS=$PASS_COUNT FAIL=$FAIL_COUNT ===="
if [[ "$FAIL_COUNT" -gt 0 ]]; then
  print -r -- "RESULT: FAILED - 检查上面探针输出"
  exit 1
fi
if [[ "$DB_MANUAL" == "1" ]]; then
  print -r -- "RESULT: PROBE READY - 经 MCP 执行探针并确认 无孤儿 / 无 MISMATCH / 无 RUNNING 滞留"
  exit 0
fi
print -r -- "RESULT: EVENTS OK - P1/P2/P3 全部通过（psql/docker 通道）"
exit 0
